version: '3.8'
services:
  xtension-bot:
    image: khapra/xtension-bot:latest
    container_name: xtension-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./plugins:/app/plugins:ro
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./.env:/app/.env:ro
      - ./VERSION:/app/VERSION:ro